apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-api-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-api-example
    spec:
      containers:
        - image: "{{ image_id }}"
          name: spring-boot-api-example
          ports:
            - containerPort: 8080
              name: http