apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-api-example
spec:
  replicas: 3
  selector:
    matchLables:
      app: spring-boot-api-example
  template:
    metadata:
      labels:
        app: spring-boot-api-example
    spec:
      containers:
        - image: cmidhun/spring-boot-api-example:0.1.0-SNAPSHOT
          name: spring-boot-api-example
          ports:
            - containerPort: 8080
              name: http