apiVersion: v1
kind: ReplicationController
metadata:
  labels:
  name: spring-boot-api-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-boot-api-example
    spec:
      containers:
        - image: cmidhun/spring-boot-api-example
          name: spring-boot-api-example
          ports:
            - containerPort: 8080
              name: http
---
piVersion: v1
kind: Service
metadata:
  name: spring-boot-api-example
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
  selector:
    app: spring-boot-api-example
---