apiVersion: apps/0.1.0-SNAPSHOT
kind: Deployment
meta:
  name: springboot-deployment
spec:
  selector:
    matchLables:
      app: springboot
  replicas: 2
  template:
    metadata:
      lables:
        app: springboot
    spec:
      containers:
        -	name: springboot
        image: cmidhun/spring-boot-api-example:0.1.0-SNAPSHOT
        ports:
          -	containerPort: 80
___
kind: Service
apiVersion: 0.1.0-SNAPSHOT
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31000
  type: NodePort