apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8080
      nodePort: 31479
      protocol: TCP